version: '3'

services:
  client:
    container_name: checkers_client
    build:
      context: ./src/checkers-client
      dockerfile: ../../ops/deployment/client.Dockerfile
    volumes:
      - ./src/checkers-client/default.conf:/etc/nginx/conf.d/default.conf

  # api:
  #   container_name: checkers_api
