version: '3'

services:
  client:
    container_name: checkers_client
    build:
      context: ./src/checkers-frontend
      dockerfile: ../../ops/deployment/frontend.Dockerfile
    ports:
      - 80:3000
    volumes:
      - ./src/checkers-frontend/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

  api:
    container_name: checkers_api
    build:
      context: ./src/checkers-backend/checkers-api
      dockerfile: ../../../ops/deployment/backend.Dockerfile
    environment:
      - ApplicationContext=Host=db;Database=postgres;Username=postgres;Password=password
    depends_on:
      - db

  db:
    image: postgres
    container_name: checkers_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
