version: '3'

services:
  client:
    container_name: checkers_client
    build:
      context: ./src/checkers-client
      dockerfile: ../../ops/deployment/client.Dockerfile
    ports:
      - 80:80
    volumes:
      - ./src/checkers-client/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

  api:
    container_name: checkers_api
    build:
      context: ./src/checkers-api
      dockerfile: ../../ops/deployment/api.Dockerfile
    environment:
      - ApplicationContext=Host=db;Database=postgres;Username=postgres;Password=password
      - QUEUE_CONNECTION_STRING=Endpoint=sb://checkers.servicebus.windows.net/;SharedAccessKeyName=Matchmaking;SharedAccessKey=hAqZAkLwm48aIT5mCY2d/qwqkPh++I5YBNdo4jl1J48=
      - QUEUE_NAME=checkers-matchmaking
    depends_on:
      - db

  db:
    image: postgres
    container_name: checkers_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
