version: '3'

services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=checkersonline.link
      - VALIDATION=http
      - STAGING=false
      - SUBDOMAINS=www
    volumes:
      - /swag:/config
      - ./ops/deployment/default.conf:/config/nginx/site-confs/default
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

  client:
    container_name: checkers_client
    build:
      context: ./src/checkers-client
      dockerfile: ../../ops/deployment/client.Dockerfile
    volumes:
      - ./src/checkers-client/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

  api:
    container_name: checkers_api
    build:
      context: ./src/checkers-api
      dockerfile: ../../ops/deployment/api.Dockerfile
    env_file:
      - ./src/checkers-api/.env
    depends_on:
      - db

  db:
    image: postgres
    container_name: checkers_db
    restart: always
    env_file:
      - ./src/checkers-db/.env
