version: '3'

services:
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - VALIDATION=http
      - TZ=America/Denver
      - URL=checkersonline.link
      - STAGING=false
      - SUBDOMAINS=www
    volumes:
      - /swag:/config
      - ./default.conf:/config/nginx/site-confs/default.conf
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

  client:
    container_name: client
    build: ./src/checkers-client
    volumes:
      - ./src/checkers-client/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    ports:
      - 80:80

  api:
    container_name: api
    build: ./src/checkers-api
