version: '3'

services:
  client:
    container_name: checkers_client
    build:
      context: ./src/checkers-client
      dockerfile: ../../ops/deployment/client.Dockerfile
    volumes:
      - ./src/checkers-client/default.conf:/etc/nginx/conf.d/default.conf

  api:
    container_name: checkers_api
    build:
      context: ./src/checkers-api
      dockerfile: ../../ops/deployment/api.Dockerfile


  db:
    image: postgres
    container_name: checkers_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
