version: '3'

services:
  dev_client:
    container_name: dev_client
    restart: always
    build:
      context: ../../src/checkers-frontend
      dockerfile: ../../ops/development/dev-frontend.Dockerfile
    ports:
      - 80:3000
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ../../src/checkers-frontend:/usr/src/app
    depends_on:
      - dev_api
  
  dev_api:
    container_name: dev_api
    restart: always
    build:
      context: ../../src/checkers-backend/checkers-api
      dockerfile: ../../../ops/development/dev-backend.Dockerfile
    environment:
      - ApplicationContext=Host=dev_db;Database=postgres;Username=postgres;Password=password
    depends_on:
      - dev_db

  dev_db:
    image: postgres
    container_name: dev_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password