// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace checkers_api.tests.Features.Game
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Game")]
    public partial class GameFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "Game.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Game", "Game", "    To ensure that my game logic is correct", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Generating default board board")]
        public void GeneratingDefaultBoardBoard()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Generating default board board", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 4
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
    testRunner.When("I start a game with players O and X", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 6
    testRunner.Then("the board should look like this", @" O |   | O |   | O |   | O |   |
   | O |   | O |   | O |   | O |
 O |   | O |   | O |   | O |   |
   |   |   |   |   |   |   |   |
   |   |   |   |   |   |   |   |
   | X |   | X |   | X |   | X |
 X |   | X |   | X |   | X |   |
   | X |   | X |   | X |   | X", ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Generating a game with a starter board")]
        public void GeneratingAGameWithAStarterBoard()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Generating a game with a starter board", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 18
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 19
  testRunner.Given("the following board with players O and X", @"  O |   | O |   | O |   | O |   |
    | O |   | O |   | O |   | O |
  O |   | O |   | O |   |   |   |
    |   |   |   |   | O |   |   |
    |   |   |   |   |   |   |   |
    | X |   | X |   | X |   | X |
  X |   | X |   | X |   | X |   |
    | X |   | X |   | X |   | X", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 30
  testRunner.Then("the board should look like this", @"  O |   | O |   | O |   | O |   |
    | O |   | O |   | O |   | O |
  O |   | O |   | O |   |   |   |
    |   |   |   |   | O |   |   |
    |   |   |   |   |   |   |   |
    | X |   | X |   | X |   | X |
  X |   | X |   | X |   | X |   |
    | X |   | X |   | X |   | X", ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Player X makes a valid move")]
        public void PlayerXMakesAValidMove()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Player X makes a valid move", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 42
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 43
  testRunner.Given("the following board with players O and X", @"  O |   | O |   | O |   | O |   |
    | O |   | O |   | O |   | O |
  O |   | O |   | O |   | O |   |
    |   |   |   |   |   |   |   |
    |   |   |   |   |   |   |   |
    | X |   | X |   | X |   | X |
  X |   | X |   | X |   | X |   |
    | X |   | X |   | X |   | X", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 54
  testRunner.When("player X makes a move from 5,1 to 4,2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 55
  testRunner.Then("the board should look like this", @"  O |   | O |   | O |   | O |   |
    | O |   | O |   | O |   | O |
  O |   | O |   | O |   | O |   |
    |   |   |   |   |   |   |   |
    |   | X |   |   |   |   |   |
    |   |   | X |   | X |   | X |
  X |   | X |   | X |   | X |   |
    | X |   | X |   | X |   | X", ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Player O makes a valid move")]
        public void PlayerOMakesAValidMove()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Player O makes a valid move", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 67
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 68
  testRunner.Given("the following board with players O and X", @"  O |   | O |   | O |   | O |   |
    | O |   | O |   | O |   | O |
  O |   | O |   | O |   | O |   |
    |   |   |   |   |   |   |   |
    |   |   |   |   |   |   |   |
    | X |   | X |   | X |   | X |
  X |   | X |   | X |   | X |   |
    | X |   | X |   | X |   | X", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 79
  testRunner.When("player O makes a move from \'2,6 > 3,5\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 80
  testRunner.Then("the board should look like this", @"  O |   | O |   | O |   | O |   |
    | O |   | O |   | O |   | O |
  O |   | O |   | O |   |   |   |
    |   |   |   |   | O |   |   |
    |   |   |   |   |   |   |   |
    | X |   | X |   | X |   | X |
  X |   | X |   | X |   | X |   |
    | X |   | X |   | X |   | X", ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Validating regular moves (excluding king moves and capturing)")]
        [NUnit.Framework.TestCaseAttribute("X", "-1", "8", "5", "0", "Source location (-1,8) is out of bounds", null)]
        [NUnit.Framework.TestCaseAttribute("X", "5", "1", "1", "-1", "Destination location (1,-1) is out of bounds", null)]
        [NUnit.Framework.TestCaseAttribute("X", "8", "8", "5", "0", "Source location (8,8) is out of bounds", null)]
        [NUnit.Framework.TestCaseAttribute("X", "5", "1", "8", "8", "Destination location (8,8) is out of bounds", null)]
        [NUnit.Framework.TestCaseAttribute("X", "0", "0", "1", "1", "Source location (0,0) does not contain a piece", null)]
        [NUnit.Framework.TestCaseAttribute("X", "2", "0", "3", "1", "Player X does not own the piece at source location (2,0)", null)]
        [NUnit.Framework.TestCaseAttribute("X", "6", "0", "5", "1", "Destination location (5,1) is not empty", null)]
        [NUnit.Framework.TestCaseAttribute("X", "5", "1", "6", "2", "Regular pieces cannot move backwards", null)]
        [NUnit.Framework.TestCaseAttribute("O", "2", "0", "1", "1", "Regular pieces cannot move backwards", null)]
        [NUnit.Framework.TestCaseAttribute("X", "5", "1", "5", "2", "Pieces can only move diagonally", null)]
        [NUnit.Framework.TestCaseAttribute("X", "5", "1", "4", "1", "Pieces can only move diagonally", null)]
        [NUnit.Framework.TestCaseAttribute("X", "5", "1", "4", "4", "Pieces can only move diagonally", null)]
        [NUnit.Framework.TestCaseAttribute("X", "5", "1", "3", "3", "Pieces can only move one square when not capturing", null)]
        [NUnit.Framework.TestCaseAttribute("X", "6", "4", "3", "7", "Pieces can only move one square when not capturing", null)]
        public void ValidatingRegularMovesExcludingKingMovesAndCapturing(string player, string sr, string sc, string dr, string dc, string error, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("player", player);
            argumentsOfScenario.Add("sr", sr);
            argumentsOfScenario.Add("sc", sc);
            argumentsOfScenario.Add("dr", dr);
            argumentsOfScenario.Add("dc", dc);
            argumentsOfScenario.Add("error", error);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validating regular moves (excluding king moves and capturing)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 92
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 93
  testRunner.Given("the following board with players O and X", @"    |   |   |   |   |   |   |   |
    |   |   |   |   |   |   |   |
  O |   |   |   |   |   |   |   |
    |   |   |   |   |   |   |   |
    |   |   |   |   |   |   |   |
    | X |   |   |   | O |   |   |
  X |   |   |   | X |   |   |   |
    |   |   |   |   |   |   |  ", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 104
  testRunner.When(string.Format("player {0} makes a move from {1},{2} to {3},{4}", player, sr, sc, dr, dc), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 105
  testRunner.Then(string.Format("the move should fail with error \'{0}\'", error), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Crowning regular piece from player X")]
        public void CrowningRegularPieceFromPlayerX()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Crowning regular piece from player X", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 124
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 125
  testRunner.Given("the following board with players O and X", @"    |   |   |   |   |   |   |   |
    | X |   |   |   |   |   |   |
  O |   |   |   |   |   |   |   |
    |   |   |   |   |   |   |   |
    |   |   |   |   |   |   |   |
    |   |   |   |   |   |   |   |
    |   |   |   |   |   |   |   |
    |   |   |   |   |   |   |  ", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 136
  testRunner.When("player X makes a move from 1,1 to 0,0", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 137
  testRunner.Then("the board should look like this", @"  X$ |   |   |   |   |   |   |   |
     |   |   |   |   |   |   |   |
   O |   |   |   |   |   |   |   |
     |   |   |   |   |   |   |   |
     |   |   |   |   |   |   |   |
     |   |   |   |   |   |   |   |
     |   |   |   |   |   |   |   |
     |   |   |   |   |   |   |  ", ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 148
  testRunner.And("the piece at 0,0 should be a king piece", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Crowning regular piece from player O")]
        public void CrowningRegularPieceFromPlayerO()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Crowning regular piece from player O", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 150
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 151
  testRunner.Given("the following board with players O and X", @"    |   |   |   |   |   |   |   |
    | X |   |   |   |   |   |   |
    |   |   |   |   |   |   |   |
    |   |   |   |   |   |   |   |
    |   |   |   |   |   |   |   |
    |   |   |   |   |   |   |   |
    |   |   |   |   |   | O |   |
    |   |   |   |   |   |   |  ", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 162
  testRunner.When("player O makes a move from 6,6 to 7,7", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 163
  testRunner.Then("the board should look like this", @"    |   |   |   |   |   |   |   |
    | X |   |   |   |   |   |   |
    |   |   |   |   |   |   |   |
    |   |   |   |   |   |   |   |
    |   |   |   |   |   |   |   |
    |   |   |   |   |   |   |   |
    |   |   |   |   |   |   |   |
    |   |   |   |   |   |   | O$", ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 174
  testRunner.And("the piece at 7,7 should be a king piece", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Generating a board with king piece already in it")]
        public void GeneratingABoardWithKingPieceAlreadyInIt()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Generating a board with king piece already in it", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 176
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 177
  testRunner.Given("the following board with players O and X", @" O$ |   |   |   |   |   |   |   |
    |   |   |   |   |   |   |   |
    |   |   |   |   |   |   |   |
    |   |   |   |   |   |   |   |
    |   |   |   |   |   |   |   |
    |   |   |   |   |   |   |   |
    |   |   |   |   |   |   |   |
    |   |   |   |   |   |   |  ", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 188
  testRunner.Then("the board should look like this", @" O$ |   |   |   |   |   |   |   |
    |   |   |   |   |   |   |   |
    |   |   |   |   |   |   |   |
    |   |   |   |   |   |   |   |
    |   |   |   |   |   |   |   |
    |   |   |   |   |   |   |   |
    |   |   |   |   |   |   |   |
    |   |   |   |   |   |   |  ", ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("King piece from player X can move backwards")]
        public void KingPieceFromPlayerXCanMoveBackwards()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("King piece from player X can move backwards", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 200
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 201
  testRunner.Given("the following board with players O and X", @"  |    |   |   |   |   |   |   |
  | X$ |   |   |   |   |   |   |
  |    |   |   |   |   |   |   |
  |    |   |   |   |   |   |   |
  |    |   |   |   |   |   |   |
  |    |   |   |   |   |   |   |
  |    |   |   |   |   | O |   |
  |    |   |   |   |   |   |  ", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 212
  testRunner.When("player X makes a move from 1,1 to 2,2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 213
  testRunner.Then("the board should look like this", @"  |   |    |   |   |   |   |   |
  |   |    |   |   |   |   |   |
  |   | X$ |   |   |   |   |   |
  |   |    |   |   |   |   |   |
  |   |    |   |   |   |   |   |
  |   |    |   |   |   |   |   |
  |   |    |   |   |   | O |   |
  |   |    |   |   |   |   |  ", ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("King piece from player O can move backwards")]
        public void KingPieceFromPlayerOCanMoveBackwards()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("King piece from player O can move backwards", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 225
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 226
  testRunner.Given("the following board with players O and X", @"  |   |   |   |   |   |    |   |
  | X |   |   |   |   |    |   |
  |   |   |   |   |   |    |   |
  |   |   |   |   |   |    |   |
  |   |   |   |   |   |    |   |
  |   |   |   |   |   |    |   |
  |   |   |   |   |   | O$ |   |
  |   |   |   |   |   |    |  ", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 237
  testRunner.When("player O makes a move from 6,6 to 5,5", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 238
  testRunner.Then("the board should look like this", @"  |   |   |   |   |    |   |   |
  | X |   |   |   |    |   |   |
  |   |   |   |   |    |   |   |
  |   |   |   |   |    |   |   |
  |   |   |   |   |    |   |   |
  |   |   |   |   | O$ |   |   |
  |   |   |   |   |    |   |   |
  |   |   |   |   |    |   |  ", ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Player X captures a piece from player O")]
        public void PlayerXCapturesAPieceFromPlayerO()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Player X captures a piece from player O", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 250
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 251
  testRunner.Given("the following board with players O and X", @"  |   |   |   |   |   |   |   |
  |   |   |   |   |   |   |   |
  |   | O |   |   |   |   |   |
  |   |   | X |   |   |   |   |
  |   |   |   |   |   |   |   |
  |   |   |   |   |   |   |   |
  |   |   |   |   |   |   |   |
  |   |   |   |   |   |   |  ", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 262
  testRunner.When("player X makes a move from 3,3 to 1,1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 263
  testRunner.Then("the board should look like this", @"  |   |   |   |   |   |   |   |
  | X |   |   |   |   |   |   |
  |   |   |   |   |   |   |   |
  |   |   |   |   |   |   |   |
  |   |   |   |   |   |   |   |
  |   |   |   |   |   |   |   |
  |   |   |   |   |   |   |   |
  |   |   |   |   |   |   |  ", ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Player O captures a piece from player X")]
        public void PlayerOCapturesAPieceFromPlayerX()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Player O captures a piece from player X", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 275
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 276
  testRunner.Given("the following board with players O and X", @"  |   |   |   |   |   |   |   |
  |   |   |   |   |   |   |   |
  |   | O |   |   |   |   |   |
  |   |   | X |   |   |   |   |
  |   |   |   |   |   |   |   |
  |   |   |   |   |   |   |   |
  |   |   |   |   |   |   |   |
  |   |   |   |   |   |   |  ", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 287
  testRunner.When("player O makes a move from 2,2 to 4,4", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 288
  testRunner.Then("the board should look like this", @"  |   |   |   |   |   |   |   |
  |   |   |   |   |   |   |   |
  |   |   |   |   |   |   |   |
  |   |   |   |   |   |   |   |
  |   |   |   | O |   |   |   |
  |   |   |   |   |   |   |   |
  |   |   |   |   |   |   |   |
  |   |   |   |   |   |   |  ", ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Player X captures a piece from player O using a king piece")]
        public void PlayerXCapturesAPieceFromPlayerOUsingAKingPiece()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Player X captures a piece from player O using a king piece", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 300
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 301
  testRunner.Given("the following board with players O and X", @"  |    |   |   |   |   |   |   |
  | X$ |   |   |   |   |   |   |
  |    | O |   |   |   |   |   |
  |    |   |   |   |   |   |   |
  |    |   |   |   |   |   |   |
  |    |   |   |   |   |   |   |
  |    |   |   |   |   |   |   |
  |    |   |   |   |   |   |  ", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 312
  testRunner.When("player X makes a move from 1,1 to 3,3", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 313
  testRunner.Then("the board should look like this", @"  |   |   |    |   |   |   |   |
  |   |   |    |   |   |   |   |
  |   |   |    |   |   |   |   |
  |   |   | X$ |   |   |   |   |
  |   |   |    |   |   |   |   |
  |   |   |    |   |   |   |   |
  |   |   |    |   |   |   |   |
  |   |   |    |   |   |   |  ", ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Player O captures a piece from player X using a king piece")]
        public void PlayerOCapturesAPieceFromPlayerXUsingAKingPiece()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Player O captures a piece from player X using a king piece", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 325
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 326
  testRunner.Given("the following board with players O and X", @"  |   |    |   |   |   |   |   |
  | X |    |   |   |   |   |   |
  |   | O$ |   |   |   |   |   |
  |   |    |   |   |   |   |   |
  |   |    |   |   |   |   |   |
  |   |    |   |   |   |   |   |
  |   |    |   |   |   |   |   |
  |   |    |   |   |   |   |  ", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 337
  testRunner.When("player O makes a move from 2,2 to 0,0", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 338
  testRunner.Then("the board should look like this", @"O$ |   |   |   |   |   |   |   |
   |   |   |   |   |   |   |   |
   |   |   |   |   |   |   |   |
   |   |   |   |   |   |   |   |
   |   |   |   |   |   |   |   |
   |   |   |   |   |   |   |   |
   |   |   |   |   |   |   |   |
   |   |   |   |   |   |   |  ", ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Player X tries a double jump when capturing")]
        public void PlayerXTriesADoubleJumpWhenCapturing()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Player X tries a double jump when capturing", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 350
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 351
  testRunner.Given("the following board with players O and X", @"  |   |   |   |   |   |   |   |
  |   |   |   |   |   |   |   |
  |   | O |   |   |   |   |   |
  |   |   |   |   |   |   |   |
  |   |   |   | O |   |   |   |
  |   |   |   |   | X |   |   |
  |   |   |   |   |   |   |   |
  |   |   |   |   |   |   |  ", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 362
  testRunner.When("player X makes a move from \'5,5 > 3,3 > 1,1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 363
  testRunner.Then("the board should look like this", @"  |   |   |   |   |   |   |   |
  | X |   |   |   |   |   |   |
  |   |   |   |   |   |   |   |
  |   |   |   |   |   |   |   |
  |   |   |   |   |   |   |   |
  |   |   |   |   |   |   |   |
  |   |   |   |   |   |   |   |
  |   |   |   |   |   |   |  ", ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Player O tries an invalid double jump")]
        public void PlayerOTriesAnInvalidDoubleJump()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Player O tries an invalid double jump", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 375
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 376
  testRunner.Given("the following board with players O and X", @"O |   |   |   |   |   |   |   |
  | X |   |   |   |   |   |   |
  |   |   |   |   |   |   |   |
  |   |   | X |   |   |   |   |
  |   |   |   | X |   |   |   |
  |   |   |   |   |   |   |   |
  |   |   |   |   |   |   |   |
  |   |   |   |   |   |   |  ", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 387
  testRunner.When("player O makes a move from \'0,0 > 2,2 > 5,5\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 388
  testRunner.Then("the move should fail with error \'Pieces can only move one square when not capturi" +
                        "ng\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
